platform :ios, '9.0'
use_frameworks!

target "wanlezu" do
    ###########################  OC  ###########################
    
    pod 'MLeaksFinder'              # https://github.com/Zepo/MLeaksFinder
    pod 'TTTAttributedLabel'        # https://github.com/TTTAttributedLabel/TTTAttributedLabel

    ########################### Swift ###########################
    pod 'Eureka'                    # https://github.com/xmartlabs/Eureka
    pod 'KeychainAccess'            # https://github.com/kishikawakatsumi/KeychainAccess
    pod 'Moya'                      # https://github.com/Moya/Moya
    pod 'ObjectMapper', '~> 2.2'    # https://github.com/Hearst-DD/ObjectMapper
    pod 'PromiseKit/Alamofire'      # https://github.com/mxcl/PromiseKit
    pod 'SnapKit', '~> 3.2.0'       # https://github.com/SnapKit/SnapKit
    pod 'SwiftyUserDefaults'        # https://github.com/radex/SwiftyUserDefaults
end
